apiVersion: v1
kind: Pod
metadata:
  name: busy-pod
spec:
  containers:
  - name: busy-container
    image: busybox
    command:
      - "sh"
      - "-c"
      - "echo 'I am busy-container' && tail -f /dev/null"
  - name: want-to-busy-container
    image: changeimagetobusybox
    command:
      - "sh"
      - "-c"
      - "echo 'I am busy-container too !!' && tail -f /dev/null"
